[package]
name = "franzi-base"
version = "0.1.0"
authors = ["Kosta Welke <kw@trinatives.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.11"
futures-preview = "0.3.0-alpha.19"

[dev-dependencies]
quickcheck = "0.9"
