[package]
name = "franzi-base"
version = "0.1.0"
authors = ["Kosta Welke <kw@trinatives.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
futures = "0.3"
snap = "0.2.5"

[dev-dependencies]
quickcheck = "0.9"
