[package]
name = "franzi-base"
version = "0.1.0"
authors = ["Kosta Welke <kw@trinatives.com>"]
edition = "2018"

[dependencies]
bytes = "1"
futures = "0.3"
snap = "1"

[dev-dependencies]
quickcheck = "1"
