[package]
name = "franzi-macros"
version = "0.1.0"
authors = ["Kosta Welke <kw@trinatives.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"
# soup = "0.5.0"

[dev-dependencies]
franzi-base = { path = "../franzi-base" }
bytes = "0.5"
