[package]
name = "franzi-macros"
version = "0.1.0"
authors = ["Kosta Welke <kw@trinatives.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6.3"
proc-macro2 = "0.4.25"
soup = "0.3.0"

[dev-dependencies]
franzi-base = { path = "../franzi-base" }
bytes = "0.5"
